version: "3"

services:
  ####################### Client Definition #######################
  frontend:
    restart: always
    container_name: client
    build:
      context: client
    volumes:
      - ./client/src/:/opt/client/src/
      - "/app/node_modules"
    ports:
      - 3000:3000
    networks:
      - default

  ####################### Database and API Definition #######################
  db:
    image: example-db-img
    container_name: example-db
    build:
      context: ./server/main/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - local-network

  api:
    image: example-api-img
    container_name: example-api
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - "./server:/usr/app"
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=main.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/db_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/db_test
    depends_on:
      - db
    networks:
      - local-network

####################### Networks Definition #######################
networks:
  default:
    driver: "bridge"
  local-network:
    driver: bridge

volumes:
  www:
