version: "3"

services:
  ####################### Client Definition #######################
  client:
    restart: always
    container_name: client
    build:
      context: client
    command: ["npm", "run", "start"]
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    volumes:
      - ./client/src/:/opt/client/src/
      - "/app/node_modules"
    ports:
      - 3000:3000
    networks:
      - default

####################### Networks Definition #######################
networks:
  default:
    driver: "bridge"
