version: "3"

services:
  ####################### Client Definition #######################
  frontend:
    restart: always
    container_name: client
    build:
      context: client
    volumes:
      - ./client/src/:/opt/client/src/
      - "/app/node_modules"
    ports:
      - 3000:3000
    networks:
      - default

####################### Networks Definition #######################
networks:
  default:
    driver: "bridge"
