name: Run Unit tests
on: [pull_request]

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update submodules
        run: make update-submodules
      - name: Run unit tests for client
        run: make client-test

  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run unit tests for server
        run: make server-test

  test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update submodules
        run: make update-submodules
      - name: Start App
        run: make run
      - name: Seed database
        run: make db-seed
      - name: Run e2e tests
        run: npm ci && npm test
