name: Run Unit Tests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checkout code and switch to client directory
        run: cd client
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install packages and run npm test
        run: |
          npm ci
          npm test
