name: Run Unit Tests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Client Unit Tests
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install and test
        run: |
          cd client
          npm ci
          npm test
